#!/usr/bin/env zsh
# vi:ft=zsh

local output_format="%(upload_date)s - %(uploader)s - %(title)s [%(width)sx%(height)s %(fps)s][%(display_id)s].%(ext)s"
local alias_axel="--downloader axel --downloader-args axel:'-n 15 -a -k'"
local alias_mp4="-f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'"
local alias_noarc="--no-download-archive"
local alias_sub="--sub-langs all --convert-subs srt --mkv --embed-subs"
local alias_mkv="--remux-video mkv"
local param_def="-N 10 --download-archive done.txt --embed-chapters"

command yt-dlp -o $output_format \
	--alias axel $alias_axel \
	--alias mp4 $alias_mp4 \
	--alias narc $alias_noarc \
	--alias sub $alias_sub \
	--alias mkv $alias_mkv \
	--download-archive "done.txt" \
	--embed-chapters \
	-N 10 \
	"$@"

